//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class amistades
    {
        public int id_usuario1 { get; set; }
        public int id_usuario2 { get; set; }
        public Nullable<System.DateTime> fecha_amistad { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual usuarios usuarios1 { get; set; }
    }
}
