//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class bloqueos
    {
        public int id_bloqueador { get; set; }
        public int id_bloqueado { get; set; }
        public Nullable<System.DateTime> fecha_bloqueo { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual usuarios usuarios1 { get; set; }
    }
}
