//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensajes
    {
        public int id_mensaje { get; set; }
        public int id_usuario_remitente { get; set; }
        public int id_usuario_destino { get; set; }
        public string texto { get; set; }
        public System.DateTime fecha_envio { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual usuarios usuarios1 { get; set; }
    }
}
