//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimientos
    {
        public int id_movimiento { get; set; }
        public int id_partida { get; set; }
        public int id_jugador { get; set; }
        public int orden { get; set; }
        public string movimiento { get; set; }
    
        public virtual participantes_partida participantes_partida { get; set; }
    }
}
