//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfiles
    {
        public int id_perfil { get; set; }
        public int id_usuario { get; set; }
        public string username { get; set; }
        public string nombre { get; set; }
        public string url { get; set; }
        public string imagen_perfil { get; set; }
        public Nullable<System.DateTime> ultimo_login { get; set; }
        public string apellido_materno { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
